package com.example.weatherapp.core.presentation.common

enum class ResourceType {
  LOADING,
  SUCCESS,
  ERROR,
  VALIDATION_ERROR,
  EMPTY_DATA,
  CONNECTION_ERROR,
  ERROR_MESSAGE,
  UNAUTHORIZED_ERROR,
  BAD_REQUEST_ERROR,
  NOT_ACTIVATED_ERROR,
  UNKNOWN_ERROR,
  FORBIDDEN_ERROR,
  BLOCK_USER_ERROR,
  SERVER_ERROR,
  NOT_ENOUGH_BALANCE,
  NOT_FOUND,
  NAVIGATION,
}